# Generated by Django 5.2.1 on 2025-05-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesUniversity', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universityCourses', to='courses.university'),
        ),
    ]
