# Generated by Django 5.2.1 on 2025-06-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_universitycourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_university', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_courses', to='courses.university'),
        ),
    ]
